### ISSUE TITLE
Installing from pip -e fails because of VERSION

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.owms#69] opened 2014-03-04 01:10 UTC
Devel branch:

```
$ pip install --upgrade -e git://github.com/saga-project/troy.git@devel#egg=troy
Obtaining troy from git+git://github.com/saga-project/troy.git@devel#egg=troy
  Updating ./Virtualenvs/AIMES/src/troy clone (to devel)
  Running setup.py egg_info for package troy
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/N/u/mturilli/Virtualenvs/AIMES/src/troy/setup.py", line 139, in <module>
        short_version, long_version, branch = get_version ([root, src_dir])
      File "/N/u/mturilli/Virtualenvs/AIMES/src/troy/setup.py", line 130, in get_version
        raise RuntimeError ("Could not extract/set version: %s" % e)
    RuntimeError: Could not extract/set version: Cannot determine version from git or ./VERSION

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/N/u/mturilli/Virtualenvs/AIMES/src/troy/setup.py", line 139, in <module>

    short_version, long_version, branch = get_version ([root, src_dir])

  File "/N/u/mturilli/Virtualenvs/AIMES/src/troy/setup.py", line 130, in get_version

    raise RuntimeError ("Could not extract/set version: %s" % e)

RuntimeError: Could not extract/set version: Cannot determine version from git or ./VERSION
```

Master branch:

```
$ pip install --upgrade -e git://github.com/saga-project/troy.git@master#egg=troy
Obtaining troy from git+git://github.com/saga-project/troy.git@master#egg=troy
  Updating ./Virtualenvs/AIMES/src/troy clone (to master)
  Running setup.py egg_info for package troy
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/N/u/mturilli/Virtualenvs/AIMES/src/troy/setup.py", line 139, in <module>
        short_version, long_version, branch = get_version ([root, src_dir])
      File "/N/u/mturilli/Virtualenvs/AIMES/src/troy/setup.py", line 130, in get_version
        raise RuntimeError ("Could not extract/set version: %s" % e)
    RuntimeError: Could not extract/set version: Cannot determine version from git or ./VERSION

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/N/u/mturilli/Virtualenvs/AIMES/src/troy/setup.py", line 139, in <module>

    short_version, long_version, branch = get_version ([root, src_dir])

  File "/N/u/mturilli/Virtualenvs/AIMES/src/troy/setup.py", line 130, in get_version

    raise RuntimeError ("Could not extract/set version: %s" % e)

RuntimeError: Could not extract/set version: Cannot determine version from git or ./VERSION
```

**Comment by andre-merzky** [comment] 2014-03-05 20:33
Hmm, this is actually working for me, in a fresh virtualenv.  And so it should, because what pip seems to do is to clone the full repo to virtualenv/src/troy, and then we are back to the normal install from git repository.  I am not sure how to debug this, will try to reproduce on other systems.  Do you have any idea?  On what machine did you try -- I assume this is your laptop?

It is also strange because we used that during the tutorial, and it worked ok.  Also, it is the same mechanism as in sagapilot and radical.utils -- do those work for you?

Thanks, A.

**Comment by marksantcroos** [comment] 2014-03-06 07:46
It it maybe related to https://github.com/saga-project/saga-python/issues/306 ?

**Comment by andre-merzky** [comment] 2014-03-06 18:40
Ach, of course!  Thanks Mark!

**Comment by andre-merzky** [comment] 2014-03-06 18:51
Good news is that the saga-python ticket can be closed.  The bad news is that it doesn't seem to relate to this problem after all... :/  Thanks though!

**Comment by mturilli** [comment] 2014-03-06 23:11
I managed to test this again (on my laptop) and it did not fail. Shall we close it?

**Comment by andre-merzky** [comment] 2014-03-06 23:15
I would be happy to close it, obviously...  If it ever happens again though, please try to create a recipe for reproduction, if possible -- that is not something I want to have lingering around...

Thanks, Andre.

**Closed as completed by andre-merzky** 2014-03-06 23:15 UTC
Labels: bug
