### ISSUE TITLE
Log all the states of a CU, avoid repetitions, and timestamp all entries

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.owms#19] opened 2014-01-26 03:22 UTC
Logs for tasks include description (missing timestamp), translation, translated (repeated twice), bound (repeated twice), dispatched (repeated twice), and done:

```
'hobot_0-task_1': t.0002 : {'inputs': [], 'executable': '/bin/sh', 'stdout': None, 'outputs': [], 'stdin': None, 'tag': 'hobot_0-task_1', 'working_directory': '/N/u/mturilli/AIMES/experiments_HPDC2014/single_workload/late_binding_32-512/scheduler_round_robin/concurrency-100/128-tasks_run-4', 'arguments': ['128-tasks_run-4-hobot_0-task_1.sh'], 'cores': 1},
2014:01:25 21:27:26 MainThread   troy.logger           : [INFO    ] workload translate: derive unit cu.0106            for t.0002
2014:01:25 21:27:26 MainThread   troy.logger           : [DEBUG   ] task state t.0002 : Translated ['Described']
2014:01:25 21:27:26 MainThread   troy.logger           : [DEBUG   ] task state t.0002 : Translated ['Described']
2014:01:25 21:27:27 MainThread   troy.logger           : [DEBUG   ] task state t.0002 : Bound      ['Bound']
2014:01:25 21:27:54 MainThread   troy.logger           : [DEBUG   ] task state t.0002 : Bound      ['Bound']
2014:01:25 21:29:16 MainThread   troy.logger           : [DEBUG   ] task state t.0002 : Dispatched ['Running']
2014:01:25 21:29:36 MainThread   troy.logger           : [DEBUG   ] task state t.0002 : Dispatched ['Running']
2014:01:25 21:29:50 MainThread   troy.logger           : [DEBUG   ] task state t.0002 : Done       ['Done']
```

CU states are incomplete including only derive, assign, and dispatch:

```
2014:01:25 21:27:26 MainThread   troy.logger           : [INFO    ] workload translate: derive unit cu.0106            for t.0002
2014:01:25 21:27:27 MainThread   troy.logger           : [INFO    ] workload schedule : assign unit cu.0106            to p.0001
2014:01:25 21:28:46 MainThread   troy.logger           : [INFO    ] workload dispatch : dispatch cu.0106            to {'type': 'PilotManager', 'uid': '52e4725147ac7468981724eb'}
```

Even accounting for the lack of introspection or information sharing with the pilot layer, we should log at least the 'done' state for the cu.

**Comment by andre-merzky** [comment] 2014-01-27 10:51
See comment on #24 -- Troy logging does not (and cannot) support timely report on internal state changes.  The message duplication is caused by some internal code path which needs state information in two different places.

I'll can log messages for CU states -- but that will blow up the log files.  At the moment, CU states are reported as sub states for the task:

```
... troy.logger : [DEBUG   ] task state t.0002 : Done       ['Done']
```

`t.0001` has one CU which is `Done`, thus the task is `Done`.  If the task would have two CUs, you would see:

```
... troy.logger : [DEBUG   ] task state t.0002 : Done       ['Done', 'Done']
```

etc.  I could also change this to 

```
... troy.logger : [DEBUG   ] task state t.0002 : Done       ['cu.0001':'Done', 'cu.0002':'Done']
```

to keep it succinct?  

As discussed in #24, I don't think that adding a separate message for the CU would actually give more information, as the logged time is the time of _query_ for state, not of the state _change_ -- so all times would be the same.

**Comment by mturilli** [comment] 2014-01-27 13:29
Thank you Andre. I see your point and as I wrote in the comments to #24, I
will be happy to get this information from the saga-pilot layer logs. I
think we might close this ticket, what do you think?

On Mon, Jan 27, 2014 at 5:51 AM, Andre Merzky notifications@github.comwrote:

> See comment on #24 https://github.com/saga-project/troy/issues/24 --
> Troy logging does not (and cannot) support timely report on internal state
> changes. The message duplication is caused by some internal code path which
> needs state information in two different places.
> 
> I'll can log messages for CU states -- but that will blow up the log
> files. At the moment, CU states are reported as sub states for the task:
> 
> ... troy.logger : [DEBUG   ] task state t.0002 : Done       ['Done']
> 
> t.0001 has one CU which is Done, thus the task is Done. If the task would
> have two CUs, you would see:
> 
> ... troy.logger : [DEBUG   ] task state t.0002 : Done       ['Done', 'Done']
> 
> etc. I could also change this to
> 
> ... troy.logger : [DEBUG   ] task state t.0002 : Done       ['cu.0001':'Done', 'cu.0002':'Done']
> 
> to keep it succinct?
> 
> As discussed in #24 https://github.com/saga-project/troy/issues/24, I
> don't think that adding a separate message for the CU would actually give
> more information, as the logged time is the time of _query_ for state,
> not of the state _change_ -- so all times would be the same.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/saga-project/troy/issues/19#issuecomment-33357648
> .

## 

Dr Matteo Turilli
Department of Electrical and Computer Engineering
Rutgers University

**Comment by andre-merzky** [comment] 2014-01-27 13:35
Yes, lets close this one, but lets .leave 24 open for the general topic of event reporting...

**Closed as completed by andre-merzky** 2014-01-27 13:35 UTC
Labels: enhancement
